const failure = {
    already_exist:{
        "code":1,
        "message":"users_already_exists"
    },
    user_name_already_exist:{
        "code":2,
        "message":"users_name_already_exists"
    },
    password_must_be_greater_than_eight_characters:{
        "code":3,
        "message":"password_must_be_greater_than_eight_characters"
    },
    user_name_is_not_exist:{
        "code":4,
        "message":"users_name_is_not_exists"
    },
    account_is_not_verified:{
        "code":5,
        "message":"account_is_not_verified"
    },
    wrong_password:{
        "code":6,
        "message":"wrong_password"
    },
    must_be_login:{
        "code":7,
        "message":"must_be_login"
    },
    token_wrong:{
        "code":8,
        "message":"token_wrong"
    },
    account_not_found:{
        "code":9,
        "message":"account_not_found"
    },
    user_name_to_short:{
        "code":10,
        "message":"user_name_to_short"
    },
    account_already_verified:{
        "code":11,
        "message":"account_already_verified"
    },
    you_must_be_login:{
        "code":11,
        "message":"you_must_be_login"
    },
    wrong_token:{
        "code":11,
        "message":"wrong_token"
    },
    email_not_send:{
        "code":19,
        "message":"email_not_send"
    },
    you_must_write_different_username:{
        "code":19,
        "message":"you_must_write_different_username"
    },
        server_error:{
        "code":19,
        "message":"server_error"
    },
    Your_new_password_cannot_be_the_same_as_your_old_password:{
        "code":19,
        "message":"Your_new_password_cannot_be_the_same_as_your_old_password"
    },
    post_not_found:{
        "code":9,
        "message":"post_not_found"
    },
    post_not_update:{
        "code":9,
        "message":"update"
    },
        
}
const successfuly = {
    register_added_and_email_sended:{
        "code":200,
        "message":"register_added_and_email_sended"
    },
    register_added_but_email_not_send:{
        "code":200,
        "message":"register_added_but_email_not_send"
    },
    login_successfuly:{
        "code":200,
        "message":"login_successfuly"
    },
    account_verified:{
        "code":200,
        "message":"account_verified"
    },
    sent_again:{
        "code":200,
        "message":"sent_again"
    },
    email_sended:{
        "code":200,
        "message":"email_sended"
    },
    email_sended:{
        "code":11,
        "message":"email_sended"
    },
    password_changed:{
        "code":11,
        "message":"password_changed"
    },
    post_adedd:{
        "code":11,
        "message":"post_adedd"
    },
    post_updated:{
        "code":11,
        "message":"post_updated"
    },
}

module.exports = {failure,successfuly};

